import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath, URL } from 'node:url';

const projectRoot = fileURLToPath(new URL('../../', import.meta.url));
const metadata = JSON.parse(await readFile(new URL('../../package.json', import.meta.url), 'utf8'));
const result = await build({
  absWorkingDir: projectRoot,
  entryPoints: ['homebridge-ui/src/main.tsx'],
  bundle: true,
  write: false,
  outdir: 'homebridge-ui/public',
  entryNames: 'settings',
  format: 'iife',
  target: ['chrome110', 'safari16'],
  // Dependencies contain multiline CSS templates with intentional whitespace.
  // Escape them as ordinary strings rather than trimming their runtime values.
  supported: { 'template-literal': false },
  minify: true,
  legalComments: 'inline',
  define: {
    'process.env.NODE_ENV': JSON.stringify('production'),
    __PLUGIN_VERSION__: JSON.stringify(metadata.version),
  },
  loader: { '.png': 'dataurl', '.svg': 'dataurl' },
});
const javascript = result.outputFiles.find((file) => file.path.endsWith('.js'))?.text;
const css = result.outputFiles.find((file) => file.path.endsWith('.css'))?.text;
if (!javascript || !css) {
  throw new Error('The settings build must include both JavaScript and Radix CSS.');
}
// Homebridge inserts this fragment in its existing iframe document. Inline every
// asset so plugin settings also work offline and with page.setContent().
const safeScript = javascript.replace(/<\/script/gi, '<\\/script');
const safeStyle = css.replace(/<\/style/gi, '<\\/style');
const fragment = '<!-- Generated by tools/ui/build.mjs; edit homebridge-ui/src instead. -->\n'
  + `<style id="hej-settings-styles">${safeStyle}</style>\n`
  + '<div id="hej-settings-root"></div>\n'
  + `<script>${safeScript}</script>\n`;
if (/<(?:html|head|body)(?:\s|>)/i.test(fragment)) {
  throw new Error('Homebridge settings must remain an HTML fragment.');
}
await mkdir(new URL('../../homebridge-ui/public/', import.meta.url), { recursive: true });
await writeFile(new URL('../../homebridge-ui/public/index.html', import.meta.url), fragment);
console.log(`Built offline settings fragment (${Math.ceil(Buffer.byteLength(fragment) / 1024)} KiB).`);
